### ISSUE TITLE
能否还原STC(tantivy引擎)中的1.28亿论文数据呢？

### ISSUE THREAD

**Issue by bigmouse0001** [cmj2002/tantivy-recover#2]
如题，我最近在研究如何利用book-searcher搜索scihub的论文数据，目前已经成功导入8000w论文数据，并且可以正常跳转。

具体是：https://github.com/book-searcher-org/book-searcher/issues/113
适配scihub的book-searcher：https://github.com/bigmouse0001/book-searcher/releases/tag/0.9.1.1

我发现有一个STC的组织，

1.  拥有1.28亿论文数据库：https://standard--template--construct-org.ipns.dweb.link/#/
2.  也是用tantivy构建的：https://izihawa.github.io/summa/core/
3.  原始数据：https://standard--template--construct-org.ipns.dweb.link/data/nexus_science
![image](https://user-images.githubusercontent.com/119995454/233087596-c43daed4-7efe-4feb-8b15-1032092e6d4e.png)

我想知道，您的程序能将这批论文的数据还原为csv吗？或者说，是否有办法将这批论文的数据还原为csv，这样就可以导入到book-searcher中了。理论上，克隆STC网站就行了，但是使用book-searcher还是要简单一点~~

我没有计算机基础，希望您有空能看一下，谢谢~

**Comment by cmj2002** [comment]
目前似乎是不行的，您的索引中包含了 `i64` 和 `f64` 类型的字段，当前版本不支持（book-searcher 没有这两种字段，所以我偷懒没写）。我可以实现一下，但是您估计得等我一段时间。此外，这 68 GB 的索引过于恐怖了，不知道程序能不能正常处理。

**Comment by bigmouse0001** [comment]
> 目前似乎是不行的，您的索引中包含了 `i64` 和 `f64` 类型的字段，当前版本不支持（book-searcher 没有这两种字段，所以我偷懒没写）。我可以实现一下，但是您估计得等我一段时间。此外，这 68 GB 的索引过于恐怖了，不知道程序能不能正常处理。

谢谢~~

**Comment by cmj2002** [comment]
我看了看索引的 `meta.json`，似乎 `Summa` 对 `tantivy` 做了一些拓展，例如其中整个 `index_attributes` 字段在 `tantivy` 中国是不存在的。尚不清楚它还做了哪些更改，这个项目可能无法满足您的需求。我仍然会继续查看项目是否可以用于索引，但是如果增加字段后仍然不行，我不会作进一步的开发。

**Comment by bigmouse0001** [comment]
好的，如果太麻烦的话就不要继续深入了～～谢谢您的答复

**Comment by cmj2002** [comment]
您能提供其他的下载方式吗？我无法下载这里面的某些文件，下载总是意外中断。

**Comment by bigmouse0001** [comment]
emmm，让我向开发者咨询一下

**Comment by bigmouse0001** [comment]
好的，由于这份数据被固定在IPFS网络中，所以不能直接使用浏览器或IPFS desktop下载。

相反，应该打开命令行版本的ipfs kubo，然后运行命令: 

- ipfs get cid

据说这样下载就不会中断，并且支持断点续传。

**Comment by cmj2002** [comment]
那既然 `summa` 支持导出，我就不再试图用本项目进行还原了。我将关闭此 issue，如果未来您有需要可以在此 issue 下评论，我会重新将其开启。
