### ISSUE TITLE
请问 Book Searcher index 还在更新吗？

### ISSUE THREAD

**Issue by liueic** [cmj2002/tantivy-recover#3]
我在网上找到最新的是 23年10月份的，不知道是否还在更新，我对这个项目很有兴趣

**Comment by cmj2002** [comment]
不太清楚，我最近已经没有在用了，book-searcher 好像也删库了？

**Comment by liueic** [comment]
> 不太清楚，我最近已经没有在用了，book-searcher 好像也删库了？

是的，我在网上只能找到一些fork的库，感谢您的回复
